#CircleCI config file
version: 2
jobs:
  build:
    docker:
      -image: circleci/python:3.7

    working directory: ~/repo

    steps:
    #1. Got repository from Github
    - checkout
    #2. Created virtual environment and installed dependencies
    - run: 
      name: install dependencies
      command: |
      python -m venv venv . venv/bin/activate
      pip install -r requirements.txt
    #3. Ran linter and unit tests
    - run:
      name: run tests
      command: |
      . venv/bin/activate
      flake8 --exclude=venv* --statistics
      pytest -v --cov=calc